name: Test code and embed into READMEs

on: push
  # pull_request:
    # branches:
      # - main
    # types:
      # - reopened
jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          token: ${{secrets.GITHUB_TOKEN}}
          ref: main
      - name: embedding readme
        uses: DGRV/markdown-embed-code@v1.0.2
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "auto commit for embedding"
          no_change: "No change on Readme."
          silent: false
