name: Test code and embed into README

on: [push]
jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}
      # - name: Set up Python
        # uses: actions/setup-python@v2
        # with:
          # python-version: 3.7
      # - name: Install dependencies and build wheel
        # run: |
            # python -m pip install --user --upgrade build
            # python -m build
            # pip install pytest
      - name: embedding readme
        uses: technology-studio-forks/markdown-embed-code@v1.1.2
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "auto commit for embedding"
          no_change: "No change on Readme."
          silent: false
